export type DirectCompanyDefinition = {
  id: string;
  name: string;
  careersUrl: string;
  logoSrc: string;
  logoAlt: string;
  logoWidth?: number;
  logoHeight?: number;
};

// Add companies here only after their matching backend parser is registered.
export const directCompanyCatalog: readonly DirectCompanyDefinition[] = [
  {
    id: "sbb",
    name: "SBB CFF FFS",
    careersUrl:
      "https://company.sbb.ch/de/jobs-karriere/jobs/offene-stellen.html?startItem=1",
    logoSrc: "/company-logos/sbb.svg",
    logoAlt: "SBB CFF FFS logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "swisscom",
    name: "Swisscom",
    careersUrl:
      "https://swisscom.wd103.myworkdayjobs.com/en-US/SwisscomExternalCareers",
    logoSrc: "/company-logos/swisscom.svg",
    logoAlt: "Swisscom logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "gilead_switzerland",
    name: "Gilead Sciences Switzerland",
    careersUrl:
      "https://gilead.wd1.myworkdayjobs.com/gileadcareers?locations=173342972c1201e6f4862b77b074df3b",
    logoSrc: "/company-logos/gilead.svg",
    logoAlt: "Gilead Sciences Switzerland logo",
    logoWidth: 149,
    logoHeight: 40,
  },
  {
    id: "galaxus",
    name: "Galaxus",
    careersUrl: "https://jobs.migros.ch/de/unsere-unternehmen/galaxus/",
    logoSrc: "/company-logos/galaxus.svg",
    logoAlt: "Galaxus logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "migros_bank",
    name: "Migros Bank",
    careersUrl:
      "https://jobs.migros.ch/de/unsere-unternehmen/migros-bank/offene-stellen",
    logoSrc: "/company-logos/migros_bank.svg",
    logoAlt: "Migros Bank logo",
    logoWidth: 36,
    logoHeight: 32,
  },
  {
    id: "die_post",
    name: "Die Post",
    careersUrl: "https://job.post.ch/search?locale=en_US",
    logoSrc: "/company-logos/die_post.svg",
    logoAlt: "Die Post logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "raiffeisen",
    name: "Raiffeisen",
    careersUrl: "https://jobs.raiffeisen.ch/",
    logoSrc: "/company-logos/raiffeisen.svg",
    logoAlt: "Raiffeisen logo",
    logoWidth: 24,
    logoHeight: 32,
  },
  {
    id: "bundesverwaltung",
    name: "Bundesverwaltung",
    careersUrl:
      "https://jobs.admin.ch/?lang=de&f=verwaltungseinheit:36497&intranet=1",
    logoSrc: "/company-logos/bundesverwaltung.svg",
    logoAlt: "Bundesverwaltung logo",
    logoWidth: 32,
    logoHeight: 32,
  },
  {
    id: "axa_schweiz",
    name: "AXA Schweiz",
    careersUrl:
      "https://careers.axa.com/careers-home/jobs?country=Switzerland&page=1",
    logoSrc: "/company-logos/axa_schweiz.svg",
    logoAlt: "AXA Schweiz logo",
    logoWidth: 32,
    logoHeight: 32,
  },
  {
    id: "sunrise",
    name: "Sunrise",
    careersUrl: "https://careers.sunrise.ch/gb/en/search-results",
    logoSrc: "/company-logos/sunrise.png",
    logoAlt: "Sunrise logo",
    logoWidth: 32,
    logoHeight: 16,
  },
  {
    id: "iss",
    name: "ISS Schweiz",
    careersUrl: "https://www.ch.issworld.com/de-ch/karriere/offene-stellen",
    logoSrc: "/company-logos/iss.svg",
    logoAlt: "ISS Schweiz logo",
    logoWidth: 32,
    logoHeight: 28,
  },
  {
    id: "accenture",
    name: "Accenture",
    careersUrl: "https://www.accenture.com/ch-en/careers/jobsearch",
    logoSrc: "/company-logos/accenture.svg",
    logoAlt: "Accenture logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "csem",
    name: "CSEM",
    careersUrl: "https://www.csem.ch/en/jobs/",
    logoSrc: "/company-logos/csem.svg",
    logoAlt: "CSEM logo",
    logoWidth: 40,
    logoHeight: 24,
  },
  {
    id: "deloitte",
    name: "Deloitte",
    careersUrl: "https://apply.deloitte.ch/CHCareers/",
    logoSrc: "/company-logos/deloitte.svg",
    logoAlt: "Deloitte logo",
    logoWidth: 40,
    logoHeight: 24,
  },
  {
    id: "zuercher_kantonalbank",
    name: "Zürcher Kantonalbank",
    careersUrl: "https://apply.refline.ch/792841/search.html",
    logoSrc: "/company-logos/zuercher_kantonalbank.svg",
    logoAlt: "Zürcher Kantonalbank logo",
    logoWidth: 48,
    logoHeight: 24,
  },
  {
    id: "flughafen_zuerich",
    name: "Flughafen Zürich",
    careersUrl:
      "https://www.flughafen-zuerich.ch/de/unternehmen/jobs/karriere/stellenangebote",
    logoSrc: "/company-logos/flughafen_zuerich.svg",
    logoAlt: "Flughafen Zürich logo",
    logoWidth: 96,
    logoHeight: 12,
  },
  {
    id: "ubs_students_graduates",
    name: "UBS Students & Graduates",
    careersUrl:
      "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25008&siteid=5131&PageType=searchResults&SearchType=linkquery&LinkID=15232#keyWordSearch=&locationSearch=Switzerland",
    logoSrc: "/company-logos/ubs.svg",
    logoAlt: "UBS logo",
    logoWidth: 64,
    logoHeight: 23,
  },
  {
    id: "abb_switzerland",
    name: "ABB Schweiz",
    careersUrl:
      "https://careers.abb/global/en/search-results?rk=l-abb-switzerland-careers&sortBy=Most%20relevant",
    logoSrc: "/company-logos/abb.svg",
    logoAlt: "ABB Schweiz logo",
    logoWidth: 64,
    logoHeight: 24,
  },
  {
    id: "huawei_switzerland",
    name: "Huawei Switzerland",
    careersUrl: "https://careers.huaweirc.ch/jobs",
    logoSrc: "/company-logos/huawei.svg",
    logoAlt: "Huawei Switzerland logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "bdo_switzerland",
    name: "BDO Switzerland",
    careersUrl: "https://www.bdo.ch/en-gb/careers/open-jobs",
    logoSrc: "/company-logos/bdo.svg",
    logoAlt: "BDO Switzerland logo",
    logoWidth: 48,
    logoHeight: 19,
  },
  {
    id: "endress_hauser_switzerland",
    name: "Endress+Hauser Switzerland",
    careersUrl:
      "https://careers.endress.com/Switzerland/content/search/?locale=en_US&currentPage=1&pageSize=20&addresses%2Fcountry=Switzerland&orderBy=datePosted&isDesc=true",
    logoSrc: "/company-logos/endress_hauser.svg",
    logoAlt: "Endress+Hauser Switzerland logo",
    logoWidth: 96,
    logoHeight: 23,
  },
  {
    id: "microsoft_switzerland",
    name: "Microsoft Switzerland",
    careersUrl:
      "https://apply.careers.microsoft.com/careers?start=0&location=Switzerland%2C+Z%C3%BCrich%2C+Z%C3%BCrich&pid=1970393556942270&sort_by=distance&filter_distance=160&filter_include_remote=1&filter_include_relocation=0",
    logoSrc: "/company-logos/microsoft.svg",
    logoAlt: "Microsoft Switzerland logo",
    logoWidth: 23,
    logoHeight: 23,
  },
  {
    id: "sap_switzerland",
    name: "SAP Switzerland",
    careersUrl: "https://jobs.sap.com/go/SAP-Jobs-in-Switzerland/915101/",
    logoSrc: "/company-logos/sap.svg",
    logoAlt: "SAP Switzerland logo",
    logoWidth: 49,
    logoHeight: 24,
  },
  {
    id: "s_peers",
    name: "s-peers",
    careersUrl: "https://s-peers.com/karriere-jobs/stellenausschreibungen/",
    logoSrc: "/company-logos/s_peers.svg",
    logoAlt: "s-peers logo",
    logoWidth: 112,
    logoHeight: 24,
  },
  {
    id: "mobiliar",
    name: "Mobiliar",
    careersUrl: "https://jobs.mobiliar.ch/go/Jobs/506974/",
    logoSrc: "/company-logos/mobiliar.svg",
    logoAlt: "Mobiliar logo",
    logoWidth: 42,
    logoHeight: 24,
  },
  {
    id: "emmi",
    name: "Emmi",
    careersUrl:
      "https://group.emmi.com/che/de/arbeiten-bei-emmi/offene-stellen",
    logoSrc: "/company-logos/emmi.svg",
    logoAlt: "Emmi logo",
    logoWidth: 47,
    logoHeight: 24,
  },
  {
    id: "sulzer_switzerland",
    name: "Sulzer Switzerland",
    careersUrl:
      "https://sulzer.wd502.myworkdayjobs.com/SulzerJobs?locationcountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/sulzer.svg",
    logoAlt: "Sulzer Switzerland logo",
    logoWidth: 142,
    logoHeight: 24,
  },
  {
    id: "siegfried",
    name: "Siegfried",
    careersUrl: "https://siegfried.wd103.myworkdayjobs.com/external",
    logoSrc: "/company-logos/siegfried.png",
    logoAlt: "Siegfried logo",
    logoWidth: 59,
    logoHeight: 24,
  },
  {
    id: "switch",
    name: "Switch",
    careersUrl: "https://recruitingapp-2563.umantis.com/Jobs/1?lang=ger",
    logoSrc: "/company-logos/switch.svg",
    logoAlt: "Switch logo",
    logoWidth: 81,
    logoHeight: 24,
  },
  {
    id: "huber_suhner_switzerland",
    name: "Huber+Suhner Switzerland",
    careersUrl: "https://recruiting.hubersuhner.com/Jobs/All",
    logoSrc: "/company-logos/huber_suhner.svg",
    logoAlt: "Huber+Suhner Switzerland logo",
    logoWidth: 92,
    logoHeight: 24,
  },
  {
    id: "stadler_it_switzerland",
    name: "Stadler IT Switzerland",
    careersUrl:
      "https://www.stadlerrail.com/de/karriere/offene-stellen?10=1077445&25=1098730&",
    logoSrc: "/company-logos/stadler.svg",
    logoAlt: "Stadler IT Switzerland logo",
    logoWidth: 142,
    logoHeight: 24,
  },
  {
    id: "ebp_switzerland",
    name: "EBP Switzerland",
    careersUrl:
      "https://www.ebp.global/ch-de/karriere/offene-stellen/stellenangebote",
    logoSrc: "/company-logos/ebp.svg",
    logoAlt: "EBP Switzerland logo",
    logoWidth: 79,
    logoHeight: 24,
  },
  {
    id: "ruag_switzerland",
    name: "RUAG Switzerland",
    careersUrl: "https://www.ruag.ch/en/working-us/job-portal",
    logoSrc: "/company-logos/ruag.svg",
    logoAlt: "RUAG Switzerland logo",
    logoWidth: 40,
    logoHeight: 24,
  },
  {
    id: "cyberlink",
    name: "Cyberlink",
    careersUrl: "https://www.cyberlink.ch/de/cyberlink/jobs",
    logoSrc: "/company-logos/cyberlink.svg",
    logoAlt: "Cyberlink logo",
    logoWidth: 118,
    logoHeight: 24,
  },
  {
    id: "ergon",
    name: "Ergon",
    careersUrl: "https://www.ergon.ch/de/karriere/jobs?showAllJobs=true",
    logoSrc: "/company-logos/ergon.svg",
    logoAlt: "Ergon logo",
    logoWidth: 82,
    logoHeight: 24,
  },
  {
    id: "logobject",
    name: "LogObject",
    careersUrl: "https://logobject.com/karriere",
    logoSrc: "/company-logos/logobject.svg",
    logoAlt: "LogObject logo",
    logoWidth: 116,
    logoHeight: 24,
  },
  {
    id: "ti8m_switzerland",
    name: "ti&m Switzerland",
    careersUrl: "https://www.ti8m.com/en/career#job",
    logoSrc: "/company-logos/ti8m.svg",
    logoAlt: "ti&m Switzerland logo",
    logoWidth: 65,
    logoHeight: 24,
  },
  {
    id: "novartis_switzerland",
    name: "Novartis Switzerland",
    careersUrl:
      "https://www.novartis.com/careers/career-search?search_api_fulltext=&country%5B%5D=LOC_CH&field_job_posted_date=All&op=Submit",
    logoSrc: "/company-logos/novartis.svg",
    logoAlt: "Novartis Switzerland logo",
    logoWidth: 160,
    logoHeight: 24,
  },
  {
    id: "pictet_switzerland",
    name: "Pictet Switzerland",
    careersUrl:
      "https://career012.successfactors.eu/career?company=banquepict&career_ns=job_listing_summary&navBarLevel=JOB_SEARCH",
    logoSrc: "/company-logos/pictet.svg",
    logoAlt: "Pictet Switzerland logo",
    logoWidth: 108,
    logoHeight: 24,
  },
  {
    id: "swiss_re",
    name: "Swiss Re",
    careersUrl: "https://www.swissre.com/careers/switzerland-careers.html",
    logoSrc: "/company-logos/swiss_re.svg",
    logoAlt: "Swiss Re logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "baloise",
    name: "Baloise",
    careersUrl: "https://www.baloise.com/de/CH/jobs.html",
    logoSrc: "/company-logos/baloise.svg",
    logoAlt: "Baloise logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "elca",
    name: "ELCA",
    careersUrl:
      "https://iaaras.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    logoSrc: "/company-logos/elca.svg",
    logoAlt: "ELCA logo",
    logoWidth: 66,
    logoHeight: 24,
  },
  {
    id: "aveniq",
    name: "Aveniq",
    careersUrl: "https://aveniq.recruitee.com/",
    logoSrc: "/company-logos/aveniq.svg",
    logoAlt: "Aveniq logo",
    logoWidth: 96,
    logoHeight: 20,
  },
  {
    id: "mimacom",
    name: "Mimacom",
    careersUrl: "https://www.mimacom.com/jobs",
    logoSrc: "/company-logos/mimacom.svg",
    logoAlt: "Mimacom logo",
    logoWidth: 138,
    logoHeight: 24,
  },
  {
    id: "unit8_switzerland",
    name: "Unit8 Switzerland",
    careersUrl: "https://unit8.com/career/",
    logoSrc: "/company-logos/unit8.svg",
    logoAlt: "Unit8 Switzerland logo",
    logoWidth: 82,
    logoHeight: 24,
  },
  {
    id: "axpo_switzerland",
    name: "Axpo Switzerland",
    careersUrl:
      "https://careers.axpo.com/jobs?split_view=true&query=&country=Switzerland",
    logoSrc: "/company-logos/axpo.svg",
    logoAlt: "Axpo Switzerland logo",
    logoWidth: 50,
    logoHeight: 24,
  },
  {
    id: "ringier",
    name: "Ringier",
    careersUrl: "https://career.ringier.ch/en/career",
    logoSrc: "/company-logos/ringier.svg",
    logoAlt: "Ringier logo",
    logoWidth: 96,
    logoHeight: 24,
  },
  {
    id: "msd",
    name: "MSD",
    careersUrl:
      "https://jobs.msd.com/gb/en/search-results?rk=page-targeted-jobs-page172-prod-DZJ1ve",
    logoSrc: "/company-logos/msd.svg",
    logoAlt: "MSD logo",
    logoWidth: 64,
    logoHeight: 24,
  },
  {
    id: "srg_ssr",
    name: "SRG SSR",
    careersUrl: "https://www.srgssr.ch/en/jobs-career/jobs",
    logoSrc: "/company-logos/srg-ssr.svg",
    logoAlt: "SRG SSR logo",
    logoWidth: 70,
    logoHeight: 24,
  },
  {
    id: "ibm",
    name: "IBM",
    careersUrl:
      "https://www.ibm.com/de-de/careers/search?field_keyword_05[0]=Switzerland",
    logoSrc: "/company-logos/ibm.svg",
    logoAlt: "IBM logo",
    logoWidth: 61,
    logoHeight: 24,
  },
  {
    id: "google",
    name: "Google",
    careersUrl:
      "https://www.google.com/about/careers/applications/jobs/results/?location=Zurich%2C%20Switzerland",
    logoSrc: "/company-logos/google.svg",
    logoAlt: "Google logo",
    logoWidth: 74,
    logoHeight: 24,
  },
  {
    id: "buhler_switzerland",
    name: "Bühler Schweiz",
    careersUrl: "https://jobs.buhlergroup.com/?lang=de",
    logoSrc: "/company-logos/buhler.svg",
    logoAlt: "Bühler Schweiz logo",
    logoWidth: 96,
    logoHeight: 24,
  },
  {
    id: "oracle_switzerland",
    name: "Oracle Switzerland",
    careersUrl:
      "https://careers.oracle.com/en/sites/jobsearch/jobs?lastSelectedFacet=locations&location=Switzerland&locationId=300000000106764&locationLevel=country&mode=location&selectedLocationsFacet=300000000106764",
    logoSrc: "/company-logos/oracle.svg",
    logoAlt: "Oracle Switzerland logo",
    logoWidth: 95,
    logoHeight: 20,
  },
  {
    id: "adnovum",
    name: "Adnovum",
    careersUrl: "https://careers.adnovum.com/search/",
    logoSrc: "/company-logos/adnovum.svg",
    logoAlt: "Adnovum logo",
    logoWidth: 96,
    logoHeight: 20,
  },
  {
    id: "ey_switzerland",
    name: "EY Switzerland",
    careersUrl:
      "https://careers.ey.com/ey/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_country=CH&optionsFacetsDD_customfield1=",
    logoSrc: "/company-logos/ey.svg",
    logoAlt: "EY Switzerland logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "eth_zurich",
    name: "ETH Zürich",
    careersUrl: "https://jobs.ethz.ch/",
    logoSrc: "/company-logos/eth_zurich.svg",
    logoAlt: "ETH Zürich logo",
    logoWidth: 96,
    logoHeight: 16,
  },
  {
    id: "siemens_switzerland",
    name: "Siemens Schweiz",
    careersUrl:
      "https://jobs.siemens.com/de_DE/externaljobs/SearchJobs/?42386=%5B812129%5D&42386_format=17546&listFilterMode=1&folderRecordsPerPage=6",
    logoSrc: "/company-logos/siemens.svg",
    logoAlt: "Siemens Schweiz logo",
    logoWidth: 88,
    logoHeight: 14,
  },
  {
    id: "kpmg_switzerland",
    name: "KPMG Switzerland",
    careersUrl: "https://kpmg.com/ch/de/karriere/offene-stellen.html",
    logoSrc: "/company-logos/kpmg.svg",
    logoAlt: "KPMG Switzerland logo",
    logoWidth: 64,
    logoHeight: 25,
  },
  {
    id: "swissgrid",
    name: "Swissgrid",
    careersUrl: "https://www.swissgrid.ch/en/home/career/jobs.html",
    logoSrc: "/company-logos/swissgrid.svg",
    logoAlt: "Swissgrid logo",
    logoWidth: 88,
    logoHeight: 22,
  },
  {
    id: "suva",
    name: "Suva",
    careersUrl:
      "https://jobs.suva.ch/search/?q=&searchResultView=LIST&pageNumber=0&facetFilters=%7B%7D&sortBy=&markerViewed=&carouselIndex=",
    logoSrc: "/company-logos/suva.svg",
    logoAlt: "Suva logo",
    logoWidth: 65,
    logoHeight: 26,
  },
  {
    id: "ao_foundation",
    name: "AO Foundation",
    careersUrl: "https://careers.aofoundation.org/search/locale=en_US",
    logoSrc: "/company-logos/ao_foundation.svg",
    logoAlt: "AO Foundation logo",
    logoWidth: 45,
    logoHeight: 24,
  },
  {
    id: "skyguide",
    name: "Skyguide",
    careersUrl: "https://jobs.skyguide.ch/search?locale=en_US",
    logoSrc: "/company-logos/skyguide.svg",
    logoAlt: "Skyguide logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "roche_switzerland",
    name: "Roche Switzerland",
    careersUrl: "https://careers.roche.com/global/en/search-results",
    logoSrc: "/company-logos/roche.svg",
    logoAlt: "Roche Switzerland logo",
    logoWidth: 46,
    logoHeight: 24,
  },
  {
    id: "logitech_switzerland",
    name: "Logitech Switzerland",
    careersUrl:
      "https://logitech.wd5.myworkdayjobs.com/Logitech?locationCountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/logitech.svg",
    logoAlt: "Logitech Switzerland logo",
    logoWidth: 74,
    logoHeight: 24,
  },
  {
    id: "swatch_group",
    name: "Swatch Group",
    careersUrl:
      "https://www.swatchgroup.com/en/job-finder?jf_country=40&domain=59&position=All&contract=All&time=All",
    logoSrc: "/company-logos/swatch_group.svg",
    logoAlt: "Swatch Group logo",
    logoWidth: 84,
    logoHeight: 24,
  },
  {
    id: "amazon_switzerland",
    name: "Amazon Switzerland",
    careersUrl:
      "https://www.amazon.jobs/content/en/locations/switzerland/zurich",
    logoSrc: "/company-logos/amazon_jobs.svg",
    logoAlt: "Amazon Switzerland logo",
    logoWidth: 42,
    logoHeight: 24,
  },
  {
    id: "cognizant_switzerland",
    name: "Cognizant Technology Solutions AG",
    careersUrl:
      "https://careers.cognizant.com/global-en/jobs/?keyword=&location=Switzerland&lat=&lng=&cname=Switzerland&ccode=CH&origin=global",
    logoSrc: "/company-logos/cognizant.svg",
    logoAlt: "Cognizant Technology Solutions AG logo",
    logoWidth: 112,
    logoHeight: 20,
  },
  {
    id: "fisba",
    name: "FISBA",
    careersUrl: "https://www.fisba.com/en/current-vacancies",
    logoSrc: "/company-logos/fisba.svg",
    logoAlt: "FISBA logo",
    logoWidth: 84,
    logoHeight: 24,
  },
  {
    id: "gritec",
    name: "GRITEC",
    careersUrl: "https://www.gritec.ch/en/career",
    logoSrc: "/company-logos/gritec.svg",
    logoAlt: "GRITEC logo",
    logoWidth: 81,
    logoHeight: 24,
  },
  {
    id: "helbling",
    name: "Helbling",
    careersUrl: "https://helbling.ch/de/karriere/jobs",
    logoSrc: "/company-logos/helbling.svg",
    logoAlt: "Helbling logo",
    logoWidth: 100,
    logoHeight: 24,
  },
  {
    id: "maerki_baumann",
    name: "Maerki Baumann",
    careersUrl: "https://www.maerki-baumann.ch/de/unsere-bank/stellenangebote",
    logoSrc: "/company-logos/maerki_baumann.svg",
    logoAlt: "Maerki Baumann logo",
    logoWidth: 18,
    logoHeight: 24,
  },
  {
    id: "electrosuisse",
    name: "Electrosuisse",
    careersUrl: "https://www.electrosuisse.ch/de/karriere/offene-stellen/",
    logoSrc: "/company-logos/electrosuisse.svg",
    logoAlt: "Electrosuisse logo",
    logoWidth: 43,
    logoHeight: 24,
  },
  {
    id: "detecon_switzerland",
    name: "Detecon Switzerland",
    careersUrl: "https://www.detecon.com/de/jobs",
    logoSrc: "/company-logos/detecon.svg",
    logoAlt: "Detecon Switzerland logo",
    logoWidth: 128,
    logoHeight: 24,
  },
  {
    id: "lufthansa_group_switzerland",
    name: "Lufthansa Group Switzerland",
    careersUrl:
      "https://apply.lufthansagroup.careers/index.php?ac=search_result&search_criterion_division%5B%5D=5926&search_criterion_division%5B%5D=9114&search_criterion_division%5B%5D=5988&search_criterion_division%5B%5D=6006&search_criterion_channel%5B%5D=12",
    logoSrc: "/company-logos/lufthansa_group.svg",
    logoAlt: "Lufthansa Group Switzerland logo",
    logoWidth: 132,
    logoHeight: 24,
  },
  {
    id: "adesso_switzerland",
    name: "Adesso Switzerland",
    careersUrl:
      "https://www.adesso.ch/de_ch/jobs-karriere/unsere-stellenangebote/",
    logoSrc: "/company-logos/adesso.svg",
    logoAlt: "Adesso Switzerland logo",
    logoWidth: 64,
    logoHeight: 24,
  },
  {
    id: "cudos",
    name: "Cudos",
    careersUrl: "https://cudos.ch/de/jobs/",
    logoSrc: "/company-logos/cudos.svg",
    logoAlt: "Cudos logo",
    logoWidth: 144,
    logoHeight: 24,
  },
  {
    id: "eraneos_switzerland",
    name: "Eraneos Switzerland",
    careersUrl:
      "https://eraneos.wd3.myworkdayjobs.com/Eraneos_External_Career_Site",
    logoSrc: "/company-logos/eraneos.svg",
    logoAlt: "Eraneos Switzerland logo",
    logoWidth: 154,
    logoHeight: 24,
  },
  {
    id: "erni_switzerland",
    name: "ERNI Switzerland",
    careersUrl: "https://www.betterask.erni/ch-en/job-opportunities/",
    logoSrc: "/company-logos/erni.svg",
    logoAlt: "ERNI Switzerland logo",
    logoWidth: 92,
    logoHeight: 24,
  },
  {
    id: "bachem",
    name: "Bachem",
    careersUrl:
      "https://careers.bachem.com/search/?createNewAlert=false&q=&optionsFacetsDD_department=&optionsFacetsDD_shifttype=&optionsFacetsDD_location=&optionsFacetsDD_country=CH&optionsFacetsDD_customfield1=",
    logoSrc: "/company-logos/bachem.svg",
    logoAlt: "Bachem logo",
    logoWidth: 87,
    logoHeight: 24,
  },
  {
    id: "georg_fischer_switzerland",
    name: "Georg Fischer Switzerland",
    careersUrl:
      "https://georgfischer.wd103.myworkdayjobs.com/GeorgFischer_Careers?locationCountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/georg_fischer.svg",
    logoAlt: "Georg Fischer Switzerland logo",
    logoWidth: 75,
    logoHeight: 24,
  },
  {
    id: "also",
    name: "ALSO",
    careersUrl:
      "https://www.also.com/ec/cms5/en_6000/6000/company/career/open-positions/index.jsp",
    logoSrc: "/company-logos/also.svg",
    logoAlt: "ALSO logo",
    logoWidth: 120,
    logoHeight: 19,
  },
  {
    id: "bedag",
    name: "Bedag",
    careersUrl: "https://www.bedag.ch/de/jobs-und-karriere/offene-stellen/",
    logoSrc: "/company-logos/bedag.svg",
    logoAlt: "Bedag logo",
    logoWidth: 101,
    logoHeight: 24,
  },
  {
    id: "nexplore",
    name: "Nexplore",
    careersUrl: "https://www.nexplore.ch/jobs",
    logoSrc: "/company-logos/nexplore.svg",
    logoAlt: "Nexplore logo",
    logoWidth: 112,
    logoHeight: 24,
  },
  {
    id: "ntt_global_data_centers_switzerland",
    name: "NTT Global Data Centers",
    careersUrl:
      "https://nttglobaldatacenters.wd501.myworkdayjobs.com/en-US/External/jobs?locations=0416448655001000c28517e560890000",
    logoSrc: "/company-logos/ntt_global_data_centers.svg",
    logoAlt: "NTT Global Data Centers logo",
    logoWidth: 87,
    logoHeight: 24,
  },
  {
    id: "teradata_switzerland",
    name: "Teradata Switzerland",
    careersUrl: "https://careers.teradata.com/jobs",
    logoSrc: "/company-logos/teradata.svg",
    logoAlt: "Teradata Switzerland logo",
    logoWidth: 120,
    logoHeight: 24,
  },
  {
    id: "swiss_life_switzerland",
    name: "Swiss Life Switzerland",
    careersUrl: "https://www.swisslife.ch/de/ueber-uns/karriere/jobs.html#",
    logoSrc: "/company-logos/swiss_life.svg",
    logoAlt: "Swiss Life Switzerland logo",
    logoWidth: 96,
    logoHeight: 24,
  },
  {
    id: "sika_switzerland",
    name: "Sika Switzerland",
    careersUrl: "https://www.sika.com/en/career/jobs.html",
    logoSrc: "/company-logos/sika.svg",
    logoAlt: "Sika Switzerland logo",
    logoWidth: 32,
    logoHeight: 28,
  },
  {
    id: "centris",
    name: "Centris",
    careersUrl: "https://www.centrisag.ch/karriere/jobs",
    logoSrc: "/company-logos/centris.svg",
    logoAlt: "Centris logo",
    logoWidth: 99,
    logoHeight: 24,
  },
  {
    id: "edorex",
    name: "Edorex",
    careersUrl: "https://edorex.ch/jobs",
    logoSrc: "/company-logos/edorex.svg",
    logoAlt: "Edorex logo",
    logoWidth: 62,
    logoHeight: 24,
  },
  {
    id: "datwyler_it_infra",
    name: "Dätwyler IT Infra",
    careersUrl:
      "https://careers.datwyler-itinfra.com/search/?locale=de_DE&searchResultView=LIST&facetFilters=%7B%22jobLocationCountry%22%3A%5B%22Schweiz%22%5D%7D&pageNumber=0",
    logoSrc: "/company-logos/datwyler_it_infra.svg",
    logoAlt: "Dätwyler IT Infra logo",
    logoWidth: 113,
    logoHeight: 24,
  },
  {
    id: "komax_group",
    name: "Komax Group",
    careersUrl:
      "https://jobs.komaxgroup.com/search/?q=&locationsearch=switzerland&searchResultView=LIST&pageNumber=0&facetFilters=%7B%7D&sortBy=&markerViewed=&carouselIndex=",
    logoSrc: "/company-logos/komax-group.svg",
    logoAlt: "Komax Group logo",
    logoWidth: 88,
    logoHeight: 24,
  },
  {
    id: "bearingpoint_switzerland",
    name: "BearingPoint Switzerland",
    careersUrl:
      "https://www.bearingpoint.com/de-ch/karriere/stellenangebote/?country=CH",
    logoSrc: "/company-logos/bearingpoint.svg",
    logoAlt: "BearingPoint Switzerland logo",
    logoWidth: 120,
    logoHeight: 20,
  },
  {
    id: "julius_baer_switzerland",
    name: "Julius Baer Switzerland",
    careersUrl:
      "https://juliusbaer.wd3.myworkdayjobs.com/en-US/External?Location_Country=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/julius-baer.svg",
    logoAlt: "Julius Baer Switzerland logo",
    logoWidth: 121,
    logoHeight: 24,
  },
  {
    id: "bkw_switzerland",
    name: "BKW Switzerland",
    careersUrl: "https://jobs.bkw.com/en/vacancies",
    logoSrc: "/company-logos/bkw.svg",
    logoAlt: "BKW Switzerland logo",
    logoWidth: 66,
    logoHeight: 24,
  },
  {
    id: "snb",
    name: "Swiss National Bank (SNB)",
    careersUrl: "https://careers.snb.ch/search/?locale=de_DE",
    logoSrc: "/company-logos/snb.svg",
    logoAlt: "Swiss National Bank logo",
    logoWidth: 146,
    logoHeight: 24,
  },
  {
    id: "amag_group",
    name: "AMAG Group",
    careersUrl: "https://jobs.amag-group.ch/",
    logoSrc: "/company-logos/amag-group.svg",
    logoAlt: "AMAG Group logo",
    logoWidth: 19,
    logoHeight: 24,
  },
  {
    id: "bayer_switzerland",
    name: "Bayer Switzerland",
    careersUrl:
      "https://talent.bayer.com/careers?location=Basel%2CBasel-City%2CSwitzerland&pid=562949977567067&job%20type=professional&job%20type=job%20starter&job%20type=student&job%20type=graduate&domain=bayer.com&sort_by=relevance&triggerGoButton=false",
    logoSrc: "/company-logos/bayer.svg",
    logoAlt: "Bayer Switzerland logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "biogen_switzerland",
    name: "Biogen Switzerland",
    careersUrl:
      "https://biibhr.wd3.myworkdayjobs.com/external?locationCountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/biogen.svg",
    logoAlt: "Biogen Switzerland logo",
    logoWidth: 69,
    logoHeight: 24,
  },
  {
    id: "bms_switzerland",
    name: "Bristol Myers Squibb Switzerland",
    careersUrl:
      "https://jobs.bms.com/careers?domain=bms.com&start=0&location=Switzerland&pid=137482241804&sort_by=distance&filter_include_remote=1&filter_include_relocation=0",
    logoSrc: "/company-logos/bms.svg",
    logoAlt: "Bristol Myers Squibb Switzerland logo",
    logoWidth: 169,
    logoHeight: 24,
  },
  {
    id: "infoguard",
    name: "InfoGuard",
    careersUrl: "https://www.infoguard.ch/en/career",
    logoSrc: "/company-logos/infoguard.svg",
    logoAlt: "InfoGuard logo",
    logoWidth: 143,
    logoHeight: 24,
  },
  {
    id: "six_group",
    name: "SIX",
    careersUrl:
      "https://jobs.six-group.com/search/?createNewAlert=false&q=&optionsFacetsDD_customfield2=&optionsFacetsDD_country=CH&optionsFacetsDD_customfield1=",
    logoSrc: "/company-logos/six.svg",
    logoAlt: "SIX logo",
    logoWidth: 66,
    logoHeight: 24,
  },
  {
    id: "comerge",
    name: "Comerge",
    careersUrl: "https://www.comerge.net/en/career#",
    logoSrc: "/company-logos/comerge.svg",
    logoAlt: "Comerge logo",
    logoWidth: 110,
    logoHeight: 24,
  },
  {
    id: "abraxas",
    name: "Abraxas Informatik AG",
    careersUrl: "https://www.abraxas.ch/de/karriere/offene-stellen",
    logoSrc: "/company-logos/abraxas.svg",
    logoAlt: "Abraxas Informatik AG logo",
    logoWidth: 29,
    logoHeight: 24,
  },
  {
    id: "akros",
    name: "AKROS AG",
    careersUrl: "https://www.akros.ch/jobs/",
    logoSrc: "/company-logos/akros.svg",
    logoAlt: "AKROS AG logo",
    logoWidth: 94,
    logoHeight: 24,
  },
  {
    id: "ametiq",
    name: "amétiq ag",
    careersUrl: "https://ametiq.ch/jobs/",
    logoSrc: "/company-logos/ametiq.svg",
    logoAlt: "amétiq ag logo",
    logoWidth: 58,
    logoHeight: 24,
  },
  {
    id: "bsi_software",
    name: "BSI Software",
    careersUrl: "https://www.bsi-software.com/en/career/jobs",
    logoSrc: "/company-logos/bsi-software.svg",
    logoAlt: "BSI Software logo",
    logoWidth: 70,
    logoHeight: 24,
  },
  {
    id: "cmi",
    name: "CM Informatik AG",
    careersUrl: "https://cmi.ch/karriere/",
    logoSrc: "/company-logos/cmi.svg",
    logoAlt: "CM Informatik AG logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "egeli_informatik",
    name: "EGELI Informatik AG",
    careersUrl: "https://egeli-informatik.ch/karriere/",
    logoSrc: "/company-logos/egeli-informatik.svg",
    logoAlt: "EGELI Informatik AG logo",
    logoWidth: 87,
    logoHeight: 24,
  },
  {
    id: "emineo",
    name: "emineo AG",
    careersUrl: "https://emineo.ch/en/career/open-positions/",
    logoSrc: "/company-logos/emineo.svg",
    logoAlt: "emineo AG logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "hostpoint",
    name: "Hostpoint AG",
    careersUrl: "https://www.hostpoint.ch/en/jobs/",
    logoSrc: "/company-logos/hostpoint.svg",
    logoAlt: "Hostpoint AG logo",
    logoWidth: 126,
    logoHeight: 24,
  },
  {
    id: "huerlimann_informatik",
    name: "Hürlimann Informatik AG",
    careersUrl:
      "https://www.hi-ag.ch/unternehmen/karriere#karriere-1266-panel-2",
    logoSrc: "/company-logos/huerlimann-informatik.svg",
    logoAlt: "Hürlimann Informatik AG logo",
    logoWidth: 108,
    logoHeight: 29,
  },
  {
    id: "infosoft",
    name: "Infosoft Systems AG",
    careersUrl: "https://infosoft.swiss/karriere/",
    logoSrc: "/company-logos/infosoft.svg",
    logoAlt: "Infosoft Systems AG logo",
    logoWidth: 104,
    logoHeight: 24,
  },
  {
    id: "isolutions",
    name: "isolutions AG",
    careersUrl: "https://www.isolutions.ch/en/career/#module-1396",
    logoSrc: "/company-logos/isolutions.svg",
    logoAlt: "isolutions AG logo",
    logoWidth: 24,
    logoHeight: 25,
  },
  {
    id: "iwf",
    name: "IWF AG",
    careersUrl: "https://www.iwf.ch/web-solutions/jobs",
    logoSrc: "/company-logos/iwf.svg",
    logoAlt: "IWF AG logo",
    logoWidth: 24,
    logoHeight: 25,
  },
  {
    id: "loewenfels",
    name: "Löwenfels Partner AG",
    careersUrl: "https://www.loewenfels.ch/karriere/",
    logoSrc: "/company-logos/loewenfels.svg",
    logoAlt: "Löwenfels Partner AG logo",
    logoWidth: 132,
    logoHeight: 24,
  },
  {
    id: "m_s_software_engineering",
    name: "M&S Software Engineering AG",
    careersUrl: "https://www.m-s.ch/karriere/offene-stellen/",
    logoSrc: "/company-logos/m-s-software-engineering.svg",
    logoAlt: "M&S Software Engineering AG logo",
    logoWidth: 110,
    logoHeight: 34,
  },
  {
    id: "opacc",
    name: "Opacc Software AG",
    careersUrl: "https://jobs.opacc.ch/",
    logoSrc: "/company-logos/opacc.svg",
    logoAlt: "Opacc Software AG logo",
    logoWidth: 84,
    logoHeight: 60,
  },
  {
    id: "panter",
    name: "Panter AG",
    careersUrl: "https://www.panter.ch/en/about-us/career/",
    logoSrc: "/company-logos/panter.svg",
    logoAlt: "Panter AG logo",
    logoWidth: 114,
    logoHeight: 30,
  },
  {
    id: "digital_architects_zurich",
    name: "Digital Architects Zurich GmbH",
    careersUrl: "https://digital-architects-zurich.ch/career/",
    logoSrc: "/company-logos/digital-architects-zurich.svg",
    logoAlt: "Digital Architects Zurich GmbH logo",
    logoWidth: 30,
    logoHeight: 30,
  },
  {
    id: "umb",
    name: "UMB AG",
    careersUrl: "https://www.umb.ch/unternehmen/it-jobs-bei-umb",
    logoSrc: "/company-logos/umb.svg",
    logoAlt: "UMB AG logo",
    logoWidth: 95,
    logoHeight: 31,
  },
  {
    id: "webtouch",
    name: "Webtouch GmbH",
    careersUrl: "https://www.webtouch.ch/karriere",
    logoSrc: "/company-logos/webtouch.svg",
    logoAlt: "Webtouch GmbH logo",
    logoWidth: 131,
    logoHeight: 17,
  },
  {
    id: "manor",
    name: "Manor AG",
    careersUrl: "https://careers.manor.ch/de/offene-stellen/offene-stellen",
    logoSrc: "/company-logos/manor.svg",
    logoAlt: "Manor AG logo",
    logoWidth: 120,
    logoHeight: 40,
  },
  {
    id: "salt_mobile",
    name: "Salt Mobile SA",
    careersUrl:
      "https://company.jobcloud.ch/de/job-list/1772460841133x163767963229093900?embedded=yes",
    logoSrc: "/company-logos/salt-mobile.svg",
    logoAlt: "Salt Mobile SA logo",
    logoWidth: 100,
    logoHeight: 40,
  },
  {
    id: "vzug",
    name: "V-ZUG AG",
    careersUrl: "https://www.vzug.com/ch/de/jobs",
    logoSrc: "/company-logos/vzug.svg",
    logoAlt: "V-ZUG AG logo",
    logoWidth: 36,
    logoHeight: 36,
  },
  {
    id: "lindt_spruengli_switzerland",
    name: "Lindt & Sprüngli (Schweiz) AG",
    careersUrl:
      "https://lindtspruengli.wd103.myworkdayjobs.com/LindtSpruengliGroupCareers?hiringCompany=6ef234644ca31000c2704c6d47960000",
    logoSrc: "/company-logos/lindt-spruengli.svg",
    logoAlt: "Lindt & Sprüngli (Schweiz) AG logo",
    logoWidth: 102,
    logoHeight: 30,
  },
  {
    id: "pwc_switzerland",
    name: "PwC Switzerland",
    careersUrl: "https://www.pwc.ch/en/careers-with-pwc/open-positions.html",
    logoSrc: "/company-logos/pwc-switzerland.svg",
    logoAlt: "PwC Switzerland logo",
    logoWidth: 53,
    logoHeight: 40,
  },
  {
    id: "tx_group",
    name: "TX Group AG",
    careersUrl: "https://jobs.tx.group/jobs",
    logoSrc: "/company-logos/tx-group.svg",
    logoAlt: "TX Group AG logo",
    logoWidth: 112,
    logoHeight: 32,
  },
  {
    id: "artificialy",
    name: "Artificialy SA",
    careersUrl: "https://www.artificialy.com/career",
    logoSrc: "/company-logos/artificialy.svg",
    logoAlt: "Artificialy SA logo",
    logoWidth: 38,
    logoHeight: 32,
  },
  {
    id: "cyon",
    name: "cyon AG",
    careersUrl: "https://www.cyon.ch/ueber-cyon/jobs",
    logoSrc: "/company-logos/cyon.svg",
    logoAlt: "cyon AG logo",
    logoWidth: 107,
    logoHeight: 40,
  },
  {
    id: "gsk_switzerland",
    name: "GSK Switzerland",
    careersUrl:
      "https://jobs.gsk.com/gb/en/search-results?keywords=&location=Switzerland&lang=en-gb",
    logoSrc: "/company-logos/gsk.svg",
    logoAlt: "GSK Switzerland logo",
    logoWidth: 40,
    logoHeight: 40,
  },
  {
    id: "sanofi_switzerland",
    name: "Sanofi Switzerland",
    careersUrl:
      "https://jobs.sanofi.com/en/search-jobs/Switzerland/2649/2/2658434/47x00016/8x01427/50/2",
    logoSrc: "/company-logos/sanofi.svg",
    logoAlt: "Sanofi Switzerland logo",
    logoWidth: 196,
    logoHeight: 30,
  },
  {
    id: "takeda_switzerland",
    name: "Takeda Switzerland",
    careersUrl: "https://jobs.takeda.com/search-jobs",
    logoSrc: "/company-logos/takeda.svg",
    logoAlt: "Takeda Switzerland logo",
    logoWidth: 113,
    logoHeight: 40,
  },
  {
    id: "jnj_switzerland",
    name: "Johnson & Johnson Switzerland",
    careersUrl:
      "https://www.careers.jnj.com/en/jobs/?search=&country=Switzerland&origin=global",
    logoSrc: "/company-logos/johnson-and-johnson.svg",
    logoAlt: "Johnson & Johnson Switzerland logo",
    logoWidth: 154,
    logoHeight: 15,
  },
  {
    id: "zurich_insurance",
    name: "Zurich Insurance",
    careersUrl:
      "https://www.careers.zurich.com/search/?createNewAlert=false&q=&locationsearch=zurich&optionsFacetsDD_shifttype=&optionsFacetsDD_department=&optionsFacetsDD_customfield3=",
    logoSrc: "/company-logos/zurich-insurance.svg",
    logoAlt: "Zurich Insurance logo",
    logoWidth: 83,
    logoHeight: 32,
  },
  {
    id: "schneider_electric_switzerland",
    name: "Schneider Electric Switzerland",
    careersUrl:
      "https://careers.se.com/jobs?lang=de-DE&country=Switzerland&page=1",
    logoSrc: "/company-logos/schneider-electric.svg",
    logoAlt: "Schneider Electric Switzerland logo",
    logoWidth: 109,
    logoHeight: 32,
  },
  {
    id: "bosch_switzerland",
    name: "Bosch Switzerland",
    careersUrl: "https://jobs.bosch.com/en/?pages=1&country=ch#",
    logoSrc: "/company-logos/bosch.svg",
    logoAlt: "Bosch Switzerland logo",
    logoWidth: 143,
    logoHeight: 32,
  },
  {
    id: "eviden_switzerland",
    name: "Eviden Switzerland",
    careersUrl: "https://eviden.com/careers/?country=CH",
    logoSrc: "/company-logos/eviden.svg",
    logoAlt: "Eviden Switzerland logo",
    logoWidth: 160,
    logoHeight: 32,
  },
  {
    id: "schindler_switzerland",
    name: "Schindler Group",
    careersUrl:
      "https://job.schindler.com/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_country=CH",
    logoSrc: "/company-logos/schindler.svg",
    logoAlt: "Schindler Group logo",
    logoWidth: 40,
    logoHeight: 40,
  },
  {
    id: "sonova_switzerland",
    name: "Sonova Group",
    careersUrl:
      "https://www.sonova.com/careers/?query-1-job-country=switzerland",
    logoSrc: "/company-logos/sonova.svg",
    logoAlt: "Sonova Group logo",
    logoWidth: 40,
    logoHeight: 40,
  },
  {
    id: "elektro_material",
    name: "Elektro-Material AG",
    careersUrl:
      "https://elektro-material.ch/de/cms/seite/offene-stellen-t33143s226453a4614994",
    logoSrc: "/company-logos/elektro-material.svg",
    logoAlt: "Elektro-Material AG logo",
    logoWidth: 49,
    logoHeight: 40,
  },
  {
    id: "csl_switzerland",
    name: "CSL Switzerland",
    careersUrl:
      "https://jobs.csl.com/en/jobs?filterrific%5Bwith_location3%5D=switzerland&filterrific%5Bsorted_by%5D=newest",
    logoSrc: "/company-logos/csl.svg",
    logoAlt: "CSL logo",
    logoWidth: 53,
    logoHeight: 40,
  },
  {
    id: "lonza_switzerland",
    name: "Lonza Switzerland",
    careersUrl: "https://www.lonza.com/careers/job-search",
    logoSrc: "/company-logos/lonza.svg",
    logoAlt: "Lonza Switzerland logo",
    logoWidth: 155,
    logoHeight: 28,
  },
  {
    id: "nestle_switzerland",
    name: "Nestlé Switzerland",
    careersUrl:
      "https://www.nestle.com/jobs/search-jobs?keyword=&country=CH&location=&career_area=All",
    logoSrc: "/company-logos/nestle.svg",
    logoAlt: "Nestlé Switzerland logo",
    logoWidth: 154,
    logoHeight: 40,
  },
  {
    id: "afry_switzerland",
    name: "AFRY Switzerland",
    careersUrl: "https://afry.com/de-ch/karriere/verfugbare-stellen",
    logoSrc: "/company-logos/afry.svg",
    logoAlt: "AFRY Switzerland logo",
    logoWidth: 174,
    logoHeight: 40,
  },
  {
    id: "digital_realty_switzerland",
    name: "Digital Realty Switzerland",
    careersUrl:
      "https://hdep.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX/jobs?location=Switzerland&locationId=300000000361301&locationLevel=country&mode=job-location",
    logoSrc: "/company-logos/digital-realty.svg",
    logoAlt: "Digital Realty Switzerland logo",
    logoWidth: 114,
    logoHeight: 40,
  },
  {
    id: "equans_switzerland",
    name: "Equans Switzerland",
    careersUrl:
      "https://www.equans.com/join-us?jobs_offer%5BrefinementList%5D%5Bcountry_en%5D%5B0%5D=Switzerland",
    logoSrc: "/company-logos/equans.svg",
    logoAlt: "Equans Switzerland logo",
    logoWidth: 134,
    logoHeight: 40,
  },
  {
    id: "bison_group",
    name: "Bison Group",
    careersUrl:
      "https://www.bison-group.com/karriere/offene-stellen/",
    logoSrc: "/company-logos/bison-group.svg",
    logoAlt: "Bison Group logo",
    logoWidth: 40,
    logoHeight: 40,
  },
];

export function getDirectCompanyByJobId(jobId: string) {
  return directCompanyCatalog.find((company) =>
    jobId.startsWith(`${company.id}-`),
  );
}
