export type DirectCompanyDefinition = {
  id: string;
  name: string;
  careersUrl: string;
  logoSrc: string;
  logoAlt: string;
  logoWidth?: number;
  logoHeight?: number;
};

// Add companies here only after their matching backend parser is registered.
export const directCompanyCatalog: readonly DirectCompanyDefinition[] = [
  {
    id: "sbb",
    name: "SBB CFF FFS",
    careersUrl:
      "https://company.sbb.ch/de/jobs-karriere/jobs/offene-stellen.html?startItem=1",
    logoSrc: "/company-logos/sbb.svg",
    logoAlt: "SBB CFF FFS logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "swisscom",
    name: "Swisscom",
    careersUrl:
      "https://swisscom.wd103.myworkdayjobs.com/en-US/SwisscomExternalCareers",
    logoSrc: "/company-logos/swisscom.svg",
    logoAlt: "Swisscom logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "galaxus",
    name: "Galaxus",
    careersUrl: "https://jobs.migros.ch/de/unsere-unternehmen/galaxus/",
    logoSrc: "/company-logos/galaxus.svg",
    logoAlt: "Galaxus logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "migros_bank",
    name: "Migros Bank",
    careersUrl:
      "https://jobs.migros.ch/de/unsere-unternehmen/migros-bank/offene-stellen",
    logoSrc: "/company-logos/migros_bank.svg",
    logoAlt: "Migros Bank logo",
    logoWidth: 36,
    logoHeight: 32,
  },
  {
    id: "die_post",
    name: "Die Post",
    careersUrl: "https://job.post.ch/search?locale=en_US",
    logoSrc: "/company-logos/die_post.svg",
    logoAlt: "Die Post logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "raiffeisen",
    name: "Raiffeisen",
    careersUrl: "https://jobs.raiffeisen.ch/",
    logoSrc: "/company-logos/raiffeisen.svg",
    logoAlt: "Raiffeisen logo",
    logoWidth: 24,
    logoHeight: 32,
  },
  {
    id: "bundesverwaltung",
    name: "Bundesverwaltung",
    careersUrl:
      "https://jobs.admin.ch/?lang=de&f=verwaltungseinheit:36497&intranet=1",
    logoSrc: "/company-logos/bundesverwaltung.svg",
    logoAlt: "Bundesverwaltung logo",
    logoWidth: 32,
    logoHeight: 32,
  },
  {
    id: "axa_schweiz",
    name: "AXA Schweiz",
    careersUrl:
      "https://careers.axa.com/careers-home/jobs?country=Switzerland&page=1",
    logoSrc: "/company-logos/axa_schweiz.svg",
    logoAlt: "AXA Schweiz logo",
    logoWidth: 32,
    logoHeight: 32,
  },
  {
    id: "sunrise",
    name: "Sunrise",
    careersUrl: "https://careers.sunrise.ch/gb/en/search-results",
    logoSrc: "/company-logos/sunrise.png",
    logoAlt: "Sunrise logo",
    logoWidth: 32,
    logoHeight: 16,
  },
  {
    id: "iss",
    name: "ISS Schweiz",
    careersUrl: "https://www.ch.issworld.com/de-ch/karriere/offene-stellen",
    logoSrc: "/company-logos/iss.svg",
    logoAlt: "ISS Schweiz logo",
    logoWidth: 32,
    logoHeight: 28,
  },
  {
    id: "accenture",
    name: "Accenture",
    careersUrl: "https://www.accenture.com/ch-en/careers/jobsearch",
    logoSrc: "/company-logos/accenture.svg",
    logoAlt: "Accenture logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "csem",
    name: "CSEM",
    careersUrl: "https://www.csem.ch/en/jobs/",
    logoSrc: "/company-logos/csem.svg",
    logoAlt: "CSEM logo",
    logoWidth: 40,
    logoHeight: 24,
  },
  {
    id: "deloitte",
    name: "Deloitte",
    careersUrl: "https://apply.deloitte.ch/CHCareers/",
    logoSrc: "/company-logos/deloitte.svg",
    logoAlt: "Deloitte logo",
    logoWidth: 40,
    logoHeight: 24,
  },
  {
    id: "zuercher_kantonalbank",
    name: "Zürcher Kantonalbank",
    careersUrl: "https://apply.refline.ch/792841/search.html",
    logoSrc: "/company-logos/zuercher_kantonalbank.svg",
    logoAlt: "Zürcher Kantonalbank logo",
    logoWidth: 48,
    logoHeight: 24,
  },
  {
    id: "flughafen_zuerich",
    name: "Flughafen Zürich",
    careersUrl:
      "https://www.flughafen-zuerich.ch/de/unternehmen/jobs/karriere/stellenangebote",
    logoSrc: "/company-logos/flughafen_zuerich.svg",
    logoAlt: "Flughafen Zürich logo",
    logoWidth: 96,
    logoHeight: 12,
  },
  {
    id: "ubs_students_graduates",
    name: "UBS Students & Graduates",
    careersUrl:
      "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad?partnerid=25008&siteid=5131&PageType=searchResults&SearchType=linkquery&LinkID=15232#keyWordSearch=&locationSearch=Switzerland",
    logoSrc: "/company-logos/ubs.svg",
    logoAlt: "UBS logo",
    logoWidth: 64,
    logoHeight: 23,
  },
  {
    id: "abb_switzerland",
    name: "ABB Schweiz",
    careersUrl:
      "https://careers.abb/global/en/search-results?rk=l-abb-switzerland-careers&sortBy=Most%20relevant",
    logoSrc: "/company-logos/abb.svg",
    logoAlt: "ABB Schweiz logo",
    logoWidth: 64,
    logoHeight: 24,
  },
  {
    id: "huawei_switzerland",
    name: "Huawei Switzerland",
    careersUrl: "https://careers.huaweirc.ch/jobs",
    logoSrc: "/company-logos/huawei.svg",
    logoAlt: "Huawei Switzerland logo",
    logoWidth: 32,
    logoHeight: 24,
  },
  {
    id: "bdo_switzerland",
    name: "BDO Switzerland",
    careersUrl: "https://www.bdo.ch/en-gb/careers/open-jobs",
    logoSrc: "/company-logos/bdo.svg",
    logoAlt: "BDO Switzerland logo",
    logoWidth: 48,
    logoHeight: 19,
  },
  {
    id: "endress_hauser_switzerland",
    name: "Endress+Hauser Switzerland",
    careersUrl:
      "https://careers.endress.com/Switzerland/content/search/?locale=en_US&currentPage=1&pageSize=20&addresses%2Fcountry=Switzerland&orderBy=datePosted&isDesc=true",
    logoSrc: "/company-logos/endress_hauser.svg",
    logoAlt: "Endress+Hauser Switzerland logo",
    logoWidth: 96,
    logoHeight: 23,
  },
  {
    id: "microsoft_switzerland",
    name: "Microsoft Switzerland",
    careersUrl:
      "https://apply.careers.microsoft.com/careers?start=0&location=Switzerland%2C+Z%C3%BCrich%2C+Z%C3%BCrich&pid=1970393556942270&sort_by=distance&filter_distance=160&filter_include_remote=1&filter_include_relocation=0",
    logoSrc: "/company-logos/microsoft.svg",
    logoAlt: "Microsoft Switzerland logo",
    logoWidth: 23,
    logoHeight: 23,
  },
  {
    id: "sap_switzerland",
    name: "SAP Switzerland",
    careersUrl: "https://jobs.sap.com/go/SAP-Jobs-in-Switzerland/915101/",
    logoSrc: "/company-logos/sap.svg",
    logoAlt: "SAP Switzerland logo",
    logoWidth: 49,
    logoHeight: 24,
  },
  {
    id: "s_peers",
    name: "s-peers",
    careersUrl: "https://s-peers.com/karriere-jobs/stellenausschreibungen/",
    logoSrc: "/company-logos/s_peers.svg",
    logoAlt: "s-peers logo",
    logoWidth: 112,
    logoHeight: 24,
  },
  {
    id: "mobiliar",
    name: "Mobiliar",
    careersUrl: "https://jobs.mobiliar.ch/go/Jobs/506974/",
    logoSrc: "/company-logos/mobiliar.svg",
    logoAlt: "Mobiliar logo",
    logoWidth: 42,
    logoHeight: 24,
  },
  {
    id: "emmi",
    name: "Emmi",
    careersUrl:
      "https://group.emmi.com/che/de/arbeiten-bei-emmi/offene-stellen",
    logoSrc: "/company-logos/emmi.svg",
    logoAlt: "Emmi logo",
    logoWidth: 47,
    logoHeight: 24,
  },
  {
    id: "sulzer_switzerland",
    name: "Sulzer Switzerland",
    careersUrl:
      "https://sulzer.wd502.myworkdayjobs.com/SulzerJobs?locationcountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/sulzer.svg",
    logoAlt: "Sulzer Switzerland logo",
    logoWidth: 142,
    logoHeight: 24,
  },
  {
    id: "siegfried",
    name: "Siegfried",
    careersUrl: "https://siegfried.wd103.myworkdayjobs.com/external",
    logoSrc: "/company-logos/siegfried.png",
    logoAlt: "Siegfried logo",
    logoWidth: 59,
    logoHeight: 24,
  },
  {
    id: "switch",
    name: "Switch",
    careersUrl: "https://recruitingapp-2563.umantis.com/Jobs/1?lang=ger",
    logoSrc: "/company-logos/switch.svg",
    logoAlt: "Switch logo",
    logoWidth: 81,
    logoHeight: 24,
  },
  {
    id: "swiss_re",
    name: "Swiss Re",
    careersUrl: "https://www.swissre.com/careers/switzerland-careers.html",
    logoSrc: "/company-logos/swiss_re.svg",
    logoAlt: "Swiss Re logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "baloise",
    name: "Baloise",
    careersUrl: "https://www.baloise.com/de/CH/jobs.html",
    logoSrc: "/company-logos/baloise.svg",
    logoAlt: "Baloise logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "elca",
    name: "ELCA",
    careersUrl:
      "https://iaaras.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs",
    logoSrc: "/company-logos/elca.svg",
    logoAlt: "ELCA logo",
    logoWidth: 66,
    logoHeight: 24,
  },
  {
    id: "aveniq",
    name: "Aveniq",
    careersUrl: "https://aveniq.recruitee.com/",
    logoSrc: "/company-logos/aveniq.svg",
    logoAlt: "Aveniq logo",
    logoWidth: 96,
    logoHeight: 20,
  },
  {
    id: "mimacom",
    name: "Mimacom",
    careersUrl: "https://www.mimacom.com/jobs",
    logoSrc: "/company-logos/mimacom.svg",
    logoAlt: "Mimacom logo",
    logoWidth: 138,
    logoHeight: 24,
  },
  {
    id: "unit8_switzerland",
    name: "Unit8 Switzerland",
    careersUrl: "https://unit8.com/career/",
    logoSrc: "/company-logos/unit8.svg",
    logoAlt: "Unit8 Switzerland logo",
    logoWidth: 82,
    logoHeight: 24,
  },
  {
    id: "axpo_switzerland",
    name: "Axpo Switzerland",
    careersUrl:
      "https://careers.axpo.com/jobs?split_view=true&query=&country=Switzerland",
    logoSrc: "/company-logos/axpo.svg",
    logoAlt: "Axpo Switzerland logo",
    logoWidth: 50,
    logoHeight: 24,
  },
  {
    id: "ringier",
    name: "Ringier",
    careersUrl: "https://career.ringier.ch/en/career",
    logoSrc: "/company-logos/ringier.svg",
    logoAlt: "Ringier logo",
    logoWidth: 96,
    logoHeight: 24,
  },
  {
    id: "msd",
    name: "MSD",
    careersUrl:
      "https://jobs.msd.com/gb/en/search-results?rk=page-targeted-jobs-page172-prod-DZJ1ve",
    logoSrc: "/company-logos/msd.svg",
    logoAlt: "MSD logo",
    logoWidth: 64,
    logoHeight: 24,
  },
  {
    id: "srg_ssr",
    name: "SRG SSR",
    careersUrl: "https://www.srgssr.ch/en/jobs-career/jobs",
    logoSrc: "/company-logos/srg-ssr.svg",
    logoAlt: "SRG SSR logo",
    logoWidth: 70,
    logoHeight: 24,
  },
  {
    id: "ibm",
    name: "IBM",
    careersUrl:
      "https://www.ibm.com/de-de/careers/search?field_keyword_05[0]=Switzerland",
    logoSrc: "/company-logos/ibm.svg",
    logoAlt: "IBM logo",
    logoWidth: 61,
    logoHeight: 24,
  },
  {
    id: "google",
    name: "Google",
    careersUrl:
      "https://www.google.com/about/careers/applications/jobs/results/?location=Zurich%2C%20Switzerland",
    logoSrc: "/company-logos/google.svg",
    logoAlt: "Google logo",
    logoWidth: 74,
    logoHeight: 24,
  },
  {
    id: "buhler_switzerland",
    name: "Bühler Schweiz",
    careersUrl: "https://jobs.buhlergroup.com/?lang=de",
    logoSrc: "/company-logos/buhler.svg",
    logoAlt: "Bühler Schweiz logo",
    logoWidth: 96,
    logoHeight: 24,
  },
  {
    id: "oracle_switzerland",
    name: "Oracle Switzerland",
    careersUrl:
      "https://careers.oracle.com/en/sites/jobsearch/jobs?lastSelectedFacet=locations&location=Switzerland&locationId=300000000106764&locationLevel=country&mode=location&selectedLocationsFacet=300000000106764",
    logoSrc: "/company-logos/oracle.svg",
    logoAlt: "Oracle Switzerland logo",
    logoWidth: 95,
    logoHeight: 20,
  },
  {
    id: "adnovum",
    name: "Adnovum",
    careersUrl: "https://careers.adnovum.com/search/",
    logoSrc: "/company-logos/adnovum.svg",
    logoAlt: "Adnovum logo",
    logoWidth: 96,
    logoHeight: 20,
  },
  {
    id: "ey_switzerland",
    name: "EY Switzerland",
    careersUrl:
      "https://careers.ey.com/ey/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_country=CH&optionsFacetsDD_customfield1=",
    logoSrc: "/company-logos/ey.svg",
    logoAlt: "EY Switzerland logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "eth_zurich",
    name: "ETH Zürich",
    careersUrl: "https://jobs.ethz.ch/",
    logoSrc: "/company-logos/eth_zurich.svg",
    logoAlt: "ETH Zürich logo",
    logoWidth: 96,
    logoHeight: 16,
  },
  {
    id: "siemens_switzerland",
    name: "Siemens Schweiz",
    careersUrl:
      "https://jobs.siemens.com/de_DE/externaljobs/SearchJobs/?42386=%5B812129%5D&42386_format=17546&listFilterMode=1&folderRecordsPerPage=6",
    logoSrc: "/company-logos/siemens.svg",
    logoAlt: "Siemens Schweiz logo",
    logoWidth: 88,
    logoHeight: 14,
  },
  {
    id: "kpmg_switzerland",
    name: "KPMG Switzerland",
    careersUrl: "https://kpmg.com/ch/de/karriere/offene-stellen.html",
    logoSrc: "/company-logos/kpmg.svg",
    logoAlt: "KPMG Switzerland logo",
    logoWidth: 64,
    logoHeight: 25,
  },
  {
    id: "swissgrid",
    name: "Swissgrid",
    careersUrl: "https://www.swissgrid.ch/en/home/career/jobs.html",
    logoSrc: "/company-logos/swissgrid.svg",
    logoAlt: "Swissgrid logo",
    logoWidth: 88,
    logoHeight: 22,
  },
  {
    id: "suva",
    name: "Suva",
    careersUrl:
      "https://jobs.suva.ch/search/?q=&searchResultView=LIST&pageNumber=0&facetFilters=%7B%7D&sortBy=&markerViewed=&carouselIndex=",
    logoSrc: "/company-logos/suva.svg",
    logoAlt: "Suva logo",
    logoWidth: 65,
    logoHeight: 26,
  },
  {
    id: "ao_foundation",
    name: "AO Foundation",
    careersUrl: "https://careers.aofoundation.org/search/locale=en_US",
    logoSrc: "/company-logos/ao_foundation.svg",
    logoAlt: "AO Foundation logo",
    logoWidth: 45,
    logoHeight: 24,
  },
  {
    id: "skyguide",
    name: "Skyguide",
    careersUrl: "https://jobs.skyguide.ch/search?locale=en_US",
    logoSrc: "/company-logos/skyguide.svg",
    logoAlt: "Skyguide logo",
    logoWidth: 24,
    logoHeight: 24,
  },
  {
    id: "roche_switzerland",
    name: "Roche Switzerland",
    careersUrl: "https://careers.roche.com/global/en/search-results",
    logoSrc: "/company-logos/roche.svg",
    logoAlt: "Roche Switzerland logo",
    logoWidth: 46,
    logoHeight: 24,
  },
  {
    id: "logitech_switzerland",
    name: "Logitech Switzerland",
    careersUrl:
      "https://logitech.wd5.myworkdayjobs.com/Logitech?locationCountry=187134fccb084a0ea9b4b95f23890dbe",
    logoSrc: "/company-logos/logitech.svg",
    logoAlt: "Logitech Switzerland logo",
    logoWidth: 74,
    logoHeight: 24,
  },
  {
    id: "swatch_group",
    name: "Swatch Group",
    careersUrl:
      "https://www.swatchgroup.com/en/job-finder?jf_country=40&domain=59&position=All&contract=All&time=All",
    logoSrc: "/company-logos/swatch_group.svg",
    logoAlt: "Swatch Group logo",
    logoWidth: 84,
    logoHeight: 24,
  },
  {
    id: "amazon_switzerland",
    name: "Amazon Switzerland",
    careersUrl:
      "https://www.amazon.jobs/content/en/locations/switzerland/zurich",
    logoSrc: "/company-logos/amazon_jobs.svg",
    logoAlt: "Amazon Switzerland logo",
    logoWidth: 42,
    logoHeight: 24,
  },
];

export function getDirectCompanyByJobId(jobId: string) {
  return directCompanyCatalog.find((company) =>
    jobId.startsWith(`${company.id}-`),
  );
}
