export const suggestedSkills = [
  "Agile Development",
  "AI Agent Development",
  "AI Application Development",
  "AI Engineering",
  "AI Integrations",
  "AI Literacy",
  "AI Model Evaluation",
  "AI Safety",
  "AI Strategy",
  "AJAX",
  "API Design",
  "API Development",
  "API Integration",
  "ASP.NET",
  "AWS",
  "AWS Lambda",
  "Accessibility",
  "Algorithms",
  "Angular",
  "Ansible",
  "Apache Kafka",
  "Application Security",
  "Architecture",
  "AsyncIO",
  "Authentication",
  "Automation",
  "Azure",
  "Bash",
  "Bootstrap",
  "CI/CD",
  "CSS",
  "Celery",
  "Chatbot Development",
  "Clean Architecture",
  "Clean Code",
  "Cloud Applications",
  "Cloud Computing",
  "Cloud Functions",
  "Cloud Security",
  "Code Review",
  "Computer Vision",
  "Continuous Deployment",
  "Continuous Integration",
  "Critical Thinking",
  "Cybersecurity",
  "Django",
  "Django REST Framework",
  "Docker",
  "Docker Compose",
  "Domain-Driven Design",
  "Elasticsearch",
  "Express.js",
  "FastAPI",
  "Firebase",
  "Flask",
  "Frontend Development",
  "Full-stack Development",
  "GCP",
  "Git",
  "GitHub",
  "GitHub Actions",
  "GitLab CI",
  "Go",
  "GraphQL",
  "HTML",
  "Helm",
  "Hugging Face",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Jira",
  "Jupyter",
  "JWT",
  "Kubernetes",
  "LangChain",
  "LangGraph",
  "Large Language Models",
  "Linux",
  "LLM Applications",
  "LLM Evaluation",
  "Machine Learning",
  "Microservices",
  "MongoDB",
  "MySQL",
  "Next.js",
  "Nginx",
  "Node.js",
  "NoSQL",
  "OAuth",
  "Object-Oriented Programming",
  "OpenAPI",
  "PHP",
  "Pandas",
  "Performance Optimization",
  "Playwright",
  "PostgreSQL",
  "Postman",
  "Problem Solving",
  "Prompt Engineering",
  "PyTorch",
  "Pytest",
  "Python",
  "QA Automation",
  "RabbitMQ",
  "React",
  "React Native",
  "Redis",
  "Refactoring",
  "Relational Databases",
  "REST API",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "SaaS Development",
  "Scikit-learn",
  "Scrum",
  "Security Best Practices",
  "Serverless",
  "Shell Scripting",
  "Software Architecture",
  "Software Design",
  "Software Development",
  "Software Engineering",
  "Software Testing",
  "Spring Boot",
  "SQL",
  "SQLite",
  "System Design",
  "Tailwind CSS",
  "Team Collaboration",
  "TensorFlow",
  "Terraform",
  "Test Automation",
  "Test-Driven Development",
  "TypeScript",
  "UI Development",
  "Unit Testing",
  "Unix",
  "UX Basics",
  "Vector Databases",
  "Vercel",
  "Vue.js",
  "Web APIs",
  "Web Development",
  "WebSockets",
  "Webpack",
  "WordPress",
  "XML",
  "YAML",
  "Zod",
  "NumPy",
  "Data Analysis",
  "Data Engineering",
  "Data Structures",
  "Data Visualization",
  "ETL",
  "MLOps",
  "MLflow",
  "RAG",
  "Retrieval-Augmented Generation",
  "Pinecone",
  "ChromaDB",
  "Qdrant",
  "Supabase",
  "Prisma",
  "SQLAlchemy",
  "ORM",
  "Pydantic",
  "Redux",
  "Zustand",
  "Svelte",
  "Nuxt.js",
  "Vite",
  "ESLint",
  "Prettier",
  "Cypress",
  "Mocha",
  "Vitest",
  "Storybook",
  "Figma",
  "Responsive Design",
  "Mobile Development",
  "Swift",
  "Kotlin",
  "Flutter",
  "Dart",
  "C",
  "C++",
  "C#",
  ".NET",
  "Graph Databases",
  "Neo4j",
  "Observability",
  "Monitoring",
  "Logging",
  "Prometheus",
  "Grafana",
  "Sentry",
  "Datadog",
  "DevOps",
  "Site Reliability Engineering",
  "Backend Development",
  "Infrastructure as Code",
  "Networking",
  "HTTP",
  "DNS",
  "TCP/IP",
  "Web Security",
  "OWASP",
  "Encryption",
  "OAuth 2.0",
  "SAML",
  "JSON",
  "gRPC",
  "Message Queues",
  "Event-Driven Architecture",
  "Distributed Systems",
  "Concurrency",
  "Multithreading",
  "Design Patterns",
  "Technical Documentation",
  "Debugging",
  "Troubleshooting",
  "Production Support",
  "Product Thinking",
  "Cross-functional Collaboration",
  "Communication",
  "Adaptability",
  "Agile Problem Solving",
];

